language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
# command to run tests
script:
  - pytest --pylint --cov

branches:
  only:
    - main
    - calc_part2
    - refractor
    - development